version: "2"

networks:
  cs30:
    external: false
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
          
services:
  server:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
        - DB_TYPE=mysql
        - DB_HOST=db:3306
        - DB_NAME=gitea
        - DB_USER=gitea
        - DB_PASSWD=gitea

    restart: always
    networks:
      cs30:
        ipv4_address: 172.19.0.5
    volumes:
      - ./git_server:/data
    ports:
      - "5000:3000"
      - "222:22"
    depends_on:
       - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      cs30:
        ipv4_address: 172.19.0.6
    volumes:
      - ./mysql:/var/lib/mysql       

  deploy_server:
    image: sudosonu/sacs_iotd:v1.0
    environment:
      - USER_UID=1000
      - USER_GID=1000

    restart: always
    networks:
      cs30:
        ipv4_address: 172.19.0.7
    volumes:
      - ./deploy/build_data:/var/build_dir/market
      - ./deploy/server_files:/var/www/html
    ports:
      - "7000:80"

