version: "2"

networks:
  cs30:
    external: false
          
services:

  gitea-server:
    image: gitea/gitea:latest
    environment:
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
    restart: always
    networks:
      - cs30
    volumes:
      - ./git_server:/data
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
       - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - cs30
    volumes:
      - ./mysql:/var/lib/mysql

  drone-server:
    image: drone/drone:1.3.0
    restart: always
    environment:
      - DRONE_GITEA_SERVER=http://gitea-server:3000
      - DRONE_SERVER_HOST=drone-server 
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_RUNNER_CAPACITY=1
      - DRONE_LOGS_COLOR=true
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      - DRONE_DEBUG=true
      - DRONE_GITEA=true
      - DRONE_ADMIN=true
      - DRONE_USER_CREATE=username,admin:true  
    networks:
      - cs30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./drone:/data    
    ports:        
      - "8000:80"
    depends_on:
      - gitea-server
