version: "2"

networks:
  cs30:
    external: false
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY}
          
services:
  server:
    image: gitea/gitea:latest
    environment:
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}

    restart: always
    networks:
      cs30:
        ipv4_address: ${GITEA_IP}
    volumes:
      - ./git_server:/data
    ports:
      - "5000:3000"
      - "222:22"
    extra_hosts:
      - "sacs.iotdeploy.com:${DEPLOY_IP}"
    depends_on:
       - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      cs30:
        ipv4_address: ${MYSQL_IP}
    volumes:
      - ./mysql:/var/lib/mysql

  deploy_server:
    image: sudosonu/sacs_iotd:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000

    restart: always
    networks:
      cs30:
        ipv4_address: ${DEPLOY_IP}
    volumes:
      - ./deploy/factory/build_dir:/var/factory/build_dir
      - ./deploy/factory/deploy_dir:/var/factory/deploy_dir
      - ./deploy/factory/tasks_dir:/var/factory/tasks_dir
      - ./deploy/server_files:/var/www/html
    ports:
      - "7000:7000"
    expose:
      - "80"

