version: "2"

networks:
  cs30:
    external: false
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY}
          
services:
  server:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
        - DB_TYPE=mysql
        - DB_HOST=db:3306
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWD=${DB_PASSWD}

    restart: always
    networks:
      cs30:
        ipv4_address: ${GITEA_IP}
    volumes:
      - ./git_server:/data
    ports:
      - "5000:3000"
      - "222:22"
    depends_on:
       - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      cs30:
        ipv4_address: ${MYSQL_IP}
    volumes:
      - ./mysql:/var/lib/mysql       

  deploy_server:
    image: sudosonu/sacs_iotd:v1.1
    environment:
      - USER_UID=1000
      - USER_GID=1000

    restart: always
    networks:
      cs30:
        ipv4_address: ${DEPLOY_IP}
    volumes:
      - ./deploy/build_data:/var/build_dir/market
      - ./deploy/server_files:/var/www/html
    ports:
      - "7000:80"

